version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: main
  labels:
    - CI/CD
    - skip_changelog

- package-ecosystem: pip
  directories:
    - "/"
    - "/.github/utils"
    - "/docker"
  schedule:
    interval: weekly
    time: "05:16"
  target-branch: main
  labels:
    - CI/CD
    - dependencies
    - skip_changelog
  groups:
    python:
      applies-to: "version-updates"
      patterns:
        - "*"
    python-security:
      applies-to: "security-updates"
      patterns:
        - "*"
