version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: main
  labels:
    - CI/CD
    - skip_changelog
- package-ecosystem: pip
  directory: "/.github/utils"
  schedule:
    interval: weekly
    time: "05:16"
  target-branch: main
  labels:
    - CI/CD
    - skip_changelog
  groups:
    ci-python:
      applies-to: "version-updates"
      patterns:
        - "*"
    ci-python-security:
      applies-to: "security-updates"
      patterns:
        - "*"
- package-ecosystem: pip
  directory: "/docker"
  schedule:
    interval: weekly
    time: "05:16"
  target-branch: main
  labels:
    - CI/CD
    - skip_changelog
  groups:
    docker-python:
      applies-to: "version-updates"
      patterns:
        - "*"
    docker-python-security:
      applies-to: "security-updates"
      patterns:
        - "*"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "05:16"
  target-branch: main
  labels:
    - dependencies
    - skip_changelog
  groups:
    pyproject:
      applies-to: "version-updates"
      patterns:
        - "*"
    pyproject-security:
      applies-to: "security-updates"
      patterns:
        - "*"
