version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: main
  labels:
    - CI/CD
    - skip_changelog
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "05:16"
  target-branch: main
  labels:
    - dependencies
    - skip_changelog
  groups:
    pyproject:
      patterns:
        - "*"
