name: DataSpaces-Entities

services:
  ds_entities_service:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      target: "${DS_ENTITIES_SERVICE_DOCKER_TARGET:-production}"
    ports:
      - "${DS_ENTITIES_SERVICE_PORT:-7000}:80"
    environment:
      DS_ENTITIES_SERVICE_BACKEND: mongodb
      DS_ENTITIES_SERVICE_MONGO_URI: "mongodb://mongodb:27017"
      DS_ENTITIES_SERVICE_X509_CERTIFICATE_FILE: "docker_security/test-client.pem"
      DS_ENTITIES_SERVICE_CA_FILE: "docker_security/test-ca.pem"
      DS_ENTITIES_SERVICE_DISABLE_AUTH_ROLE_CHECKS: "1"
      DS_ENTITIES_SERVICE_DEBUG: "1"
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    networks:
      - ds_entities_service_net
    volumes:
      - "../:/app"  # should map the repository root to /app in the container
    user: "1000:1000"  # To ensure files (logs) created in the container are owned by the host user
    stop_grace_period: 1s

  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - ds_entities_service_net
    volumes:
      - "./docker_init/create_x509_user.js:/docker-entrypoint-initdb.d/0_create_x509_user.js"
      - "../docker_security:/mongo_tls"
    command: --tlsMode allowTLS --tlsCertificateKeyFile /mongo_tls/test-server1.pem --tlsCAFile /mongo_tls/test-ca.pem
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://root:root@localhost:27017/?authSource=admin --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb_gui:
    image: mongo-express:1
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - ds_entities_service_net
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true

networks:
  ds_entities_service_net:
