name: CI - Check dependencies PR

on:
  schedule:
    # At 7:30 every Monday (5:30 UTC)
    - cron: "30 5 * * 1"
  workflow_dispatch:

jobs:
  check-dependencies:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_check_pyproject_dependencies.yml@v2.7.3
    if: github.repository_owner == 'M-ERA-NET-MEDIATE'
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      target_branch: "main"
      python_version: "3.10"
      install_extras: "[dev]"
      pr_labels: "CI/CD,skip_changelog"
    secrets:
      PAT: ${{ secrets.TEAM40_PAT }}
